"""Recent-notes dashboard for the vault (v1.7).

Generates a vault-root note ("Recent Notes.md") listing every note created
or modified in the last N days, grouped by category folder — plain Markdown
wikilinks, so it renders without any plugin. Refreshed by /dashboard or a
silent weekly job (no Telegram messages — it only rewrites the note).
"""
from __future__ import annotations

import logging
import os
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# Same reserved prefixes as the organizer — dashboards never live there
_RESERVED_PREFIXES = ("00_", "90_", "99_")
DASHBOARD_FILENAME = "Recent Notes.md"


def dashboard_days() -> int:
    try:
        return max(1, int(os.getenv("DASHBOARD_DAYS", "7")))
    except ValueError:
        return 7


def _note_title(path: Path) -> str:
    """Extract the `title:` frontmatter field (cheap single-file read)."""
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as fh:
            for line in fh.read(2000).splitlines()[:15]:
                s = line.strip()
                if s.startswith("title:"):
                    t = s[6:].strip().strip('"').strip("'")
                    if t:
                        return t
    except OSError as e:
        logger.debug(f"Could not read title from {path}: {e}")
    return path.stem


def collect_recent_notes(
    vault_root: str, days: int = 7
) -> Dict[str, List[Tuple[float, Path, str]]]:
    """
    Group notes created/modified within `days` by category folder.
    A single unreadable folder never aborts the scan (same policy as /organize).
    """
    vault = Path(vault_root)
    cutoff = time.time() - days * 86400
    groups: Dict[str, List[Tuple[float, Path, str]]] = {}
    try:
        children = list(vault.iterdir())
    except OSError as e:
        logger.error(f"Could not list vault {vault}: {e}")
        return groups
    for child in children:
        if child.name.startswith(".") or child.name.startswith(_RESERVED_PREFIXES):
            continue
        try:
            if not child.is_dir():
                continue
            for note in child.rglob("*.md"):
                st = note.stat()
                # mtime = created-or-modified activity (bot writes notes once,
                # so mtime ≈ created; edits keep the note "recent"). Using
                # birthtime too would misbehave: macOS birthtime ignores utime.
                when = st.st_mtime
                if when < cutoff:
                    continue
                groups.setdefault(child.name, []).append(
                    (when, note, _note_title(note))
                )
        except OSError as e:
            logger.warning(f"Skipping unreadable folder {child}: {e}")
            continue
    for notes in groups.values():
        notes.sort(key=lambda t: -t[0])  # newest first within category
    return groups


def build_dashboard_markdown(
    vault_root: str, days: int = 7, limit: int = 50
) -> str:
    """Render the dashboard note. Empty string when nothing is recent."""
    groups = collect_recent_notes(vault_root, days)
    if not groups:
        return ""
    lines = [
        "---",
        "title: Recent Notes",
        "category: Dashboard",
        "tags: [dashboard]",
        "---",
        "",
        "# 🆕 Recent Notes",
        f"_Notes from the last **{days} day(s)** — generated by the bot on "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}. Refresh with `/dashboard`._",
        "",
    ]
    total = 0
    # Biggest categories first
    for cat in sorted(groups, key=lambda c: -len(groups[c])):
        notes = groups[cat]
        lines.append(f"## {cat} ({len(notes)})")
        lines.append("")
        for when, note, title in notes:
            if total >= limit:
                lines.append(f"_… more notes omitted (limit {limit})_")
                break
            rel = note.relative_to(Path(vault_root)).with_suffix("")
            stamp = datetime.fromtimestamp(when).strftime("%Y-%m-%d %H:%M")
            lines.append(f"- [[{rel}|{title}]] — {stamp}")
            total += 1
        lines.append("")
        if total >= limit:
            break
    return "\n".join(lines).rstrip() + "\n"


def write_dashboard(
    vault_root: str, days: Optional[int] = None, limit: int = 50
) -> Optional[Path]:
    """
    Write Recent Notes.md at the vault root. Returns the path, or None when
    there are no recent notes or the write failed. Never raises.
    """
    days = days or dashboard_days()
    try:
        md = build_dashboard_markdown(vault_root, days=days, limit=limit)
        if not md:
            return None
        out = Path(vault_root) / DASHBOARD_FILENAME
        out.write_text(md, encoding="utf-8")
        logger.info(f"Dashboard written: {out}")
        return out
    except OSError as e:
        logger.error(f"Could not write dashboard: {e}")
        return None
