#!/usr/bin/env bash
#
# backup_recent.sh — Backup of notes/attachments created in the last N days
#
# PURPOSE
#   Safety net that is FULLY INDEPENDENT from:
#     - the Docker container (runs on the host, touches no container state)
#     - the rclone mount write-path (reads the vault read-only; writes to a
#       plain local directory that is NOT part of the rclone/Drive chain)
#
# WHAT IT COPIES
#   - All *.md notes modified in the last $DAYS days (whole vault tree)
#   - All files under 90_Attachments/ (docs, audio, thumbnails, BookTexts,
#     handwriting samples…) modified in the last $DAYS days
#
# WHERE IT WRITES
#   $BACKUP_ROOT/<timestamp>/   preserving the vault directory structure
#   $BACKUP_ROOT/<timestamp>/_manifest.txt   (list of files + sizes)
#   $BACKUP_ROOT/latest -> newest run (symlink, for easy restore)
#
# USAGE (on the server, as root or the vault owner)
#   sudo bash backup_recent.sh                # backup last 3 days
#   sudo bash backup_recent.sh 7              # backup last 7 days
#   sudo bash backup_recent.sh 3 --dry-run    # show what would be copied
#   sudo bash backup_recent.sh --setup-cron   # install daily cron job (03:30)
#
# RESTORE (single file / whole run)
#   cp -a $BACKUP_ROOT/latest/10_Categories/Foo/note.md /mnt/obsidian-vault/10_Categories/Foo/
#
set -euo pipefail

# ----------------------------------------------------------------- config ---
DAYS="${1:-3}"
DRY_RUN=0
SETUP_CRON=0
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=1 ;;
        --setup-cron) SETUP_CRON=1 ;;
        [0-9]*) DAYS="$arg" ;;
    esac
done

# Vault on the HOST (the rclone mount point — read-only for this script).
# Order: explicit env var > docker-compose default > common rclone paths.
VAULT_DIR="${VAULT_DIR:-}"
if [ -z "$VAULT_DIR" ]; then
    for d in /srv/obsidian-vault /mnt/obsidian-vault /mnt/gdrive /mnt/drive; do
        [ -d "$d" ] && VAULT_DIR="$d" && break
    done
fi
[ -z "$VAULT_DIR" ] && { echo "❌ Vault dir not found. Run: VAULT_DIR=/your/mount bash $0"; exit 1; }

# Backup target: plain local fs — outside the vault, outside Docker volumes.
BACKUP_ROOT="${BACKUP_ROOT:-/root/obsidian-backups}"
STAMP="$(date +%Y%m%d_%H%M%S)"
DEST="$BACKUP_ROOT/$STAMP"
CRON_FILE="/etc/cron.d/obsidian-recent-backup"

# ----------------------------------------------------------------- cron -----
if [ "$SETUP_CRON" = "1" ]; then
    SELF="$(readlink -f "$0")"
    echo "Installing daily backup cron (03:30, last ${DAYS} day(s)) -> $CRON_FILE"
    printf '%s\n' \
        "# Backup recent Obsidian notes/attachments (generated by backup_recent.sh)" \
        "30 3 * * * root VAULT_DIR=$VAULT_DIR BACKUP_ROOT=$BACKUP_ROOT $SELF $DAYS >> /var/log/obsidian-backup.log 2>&1" \
        > "$CRON_FILE"
    chmod 644 "$CRON_FILE"
    echo "✅ Installed. Logs: /var/log/obsidian-backup.log"
    exit 0
fi

# ------------------------------------------------------------ sanity checks -
[ -d "$VAULT_DIR" ] || { echo "❌ Vault dir '$VAULT_DIR' does not exist."; exit 1; }

# Portable absolute-path resolution that works EVEN IF the target does not
# exist yet (first run: BACKUP_ROOT/timestamp never exists).
# Resolves the deepest existing ancestor with `cd` + `pwd -P` (physical
# path — consistent on macOS /tmp vs /private/tmp and any symlinked mount),
# then re-appends the missing tail. Produces the SAME canonical form for
# both inputs, so the prefix check below never false-positives/negatives.
resolve_path() {
    local p dir base
    p="$1"
    [ -z "$p" ] && printf '.' && return
    case "$p" in */) p="${p%/}" ;; esac
    [ "$p" = "/" ] && { printf '/'; return; }
    dir="$(dirname "$p")"
    base="$(basename "$p")"
    while [ ! -e "$dir" ] && [ "$dir" != "/" ]; do
        base="$(basename "$dir")/$base"
        dir="$(dirname "$dir")"
    done
    local resolved
    resolved="$(cd "$dir" 2>/dev/null && pwd -P)" || resolved="$dir"
    case "$base" in
        "" | ".") printf '%s' "$resolved" ;;
        *)        printf '%s/%s' "${resolved%/}" "$base" ;;
    esac
}

RL_B="$(resolve_path "$BACKUP_ROOT")"
RL_V="$(resolve_path "$VAULT_DIR")"
# Trailing slash: prevents false positives on sibling dirs like
# /srv/obsidian-vault-backup (which also starts with /srv/obsidian-vault).
case "$RL_B/" in
    "$RL_V"/*) echo "❌ BACKUP_ROOT is inside the vault/mount — not safe. Choose another path."; exit 1 ;;
esac

# mountpoint(1) is Linux-only; fall back to parsing `mount` output.
if command -v mountpoint >/dev/null 2>&1; then
    mountpoint -q "$VAULT_DIR" && SRC_IS_MOUNT=1 || SRC_IS_MOUNT=0
else
    mount | grep -qF " on $RL_V " && SRC_IS_MOUNT=1 || SRC_IS_MOUNT=0
fi
case "$(readlink -f "$BACKUP_ROOT")" in
    "$(readlink -f "$VAULT_DIR")"*) echo "❌ BACKUP_ROOT is inside the vault/mount — not safe. Choose another path."; exit 1 ;;
esac

echo "══════════════════════════════════════════════════════"
echo " Vault source : $VAULT_DIR  (rclone mount: $([ "$SRC_IS_MOUNT" = 1 ] && echo yes || echo no))"
echo " Backup to    : $DEST"
echo " Window       : last $DAYS day(s)"
[ "$DRY_RUN" = 1 ] && echo " MODE         : DRY-RUN (nothing written)"
echo "══════════════════════════════════════════════════════"

# --------------------------------------------------- find recent files ------
# Notes (.md) anywhere in the vault + every attachment under 90_Attachments.
# -print0 / read -d '' handles spaces/unicode in filenames (pt-PT titles etc.).
FILELIST="$(mktemp)"
trap 'rm -f "$FILELIST"' EXIT
find "$VAULT_DIR" \
    \( -path "$VAULT_DIR/.obsidian" -o -path "$VAULT_DIR/.git" \) -prune -o \
    -type f \( -name "*.md" -o -path "$VAULT_DIR/90_Attachments/*" \) \
    -mtime "-$DAYS" -print0 > "$FILELIST"

# Count + total size using only bash builtins (portable: GNU + BSD/macOS).
COUNT=0
TOTAL_BYTES=0
while IFS= read -r -d '' f; do
    COUNT=$((COUNT + 1))
    SZ=$(wc -c < "$f" | tr -d ' ')
    TOTAL_BYTES=$((TOTAL_BYTES + SZ))
done < "$FILELIST"

if [ "$COUNT" -eq 0 ]; then
    echo "ℹ️  No files modified in the last $DAYS day(s). Nothing to do."
    exit 0
fi
SIZE_HUMAN=$(( TOTAL_BYTES / 1048576 ))MB
if [ $TOTAL_BYTES -lt 1048576 ]; then
    SIZE_HUMAN=$(( TOTAL_BYTES / 1024 ))KB
fi
echo "→ $COUNT file(s), ~$SIZE_HUMAN"

if [ "$DRY_RUN" = 1 ]; then
    while IFS= read -r -d '' f; do echo "${f#"$VAULT_DIR"/}"; done < "$FILELIST"
    exit 0
fi

# ------------------------------------------------------------------ copy ----
# Copy loop preserves the vault-relative structure; works on any coreutils.
mkdir -p "$DEST"
while IFS= read -r -d '' f; do
    rel="${f#"$VAULT_DIR"/}"
    mkdir -p "$DEST/$(dirname "$rel")"
    cp -a "$f" "$DEST/$rel"
done < "$FILELIST"

# Manifest: byte size + vault-relative path, for audit/restore.
: > "$DEST/_manifest.txt"
while IFS= read -r -d '' f; do
    printf '%s %s\n' "$(wc -c < "$f" | tr -d ' ')" "${f#"$VAULT_DIR"/}" >> "$DEST/_manifest.txt"
done < "$FILELIST"
{
    echo "backup_run: $STAMP"
    echo "window_days: $DAYS"
    echo "vault_source: $VAULT_DIR"
    echo "files: $COUNT  total_bytes: $TOTAL_BYTES"
} > "$DEST/_info.txt"

# 'latest' pointer for painless restore
ln -sfn "$DEST" "$BACKUP_ROOT/latest"

# --------------------------------------------------- retention (30 runs) ----
# Keep the 30 most recent runs; delete older ones (each run is small — only
# recent files — so 30 runs is a generous safety window).
ls -1dt "$BACKUP_ROOT"/20* 2>/dev/null | tail -n +31 | while read -r old; do
    rm -rf "$old"
    echo "🧹 Pruned old backup: $old"
done

echo ""
echo "✅ Backup complete → $DEST ($COUNT file(s), ~$SIZE_HUMAN)"
echo "   Restore example:"
echo "     cp -a $BACKUP_ROOT/latest/<vault-relative-path> $VAULT_DIR/<same-path>"
